# **Aprendizado Supervisionado: Classificação**

*Em tarefas preditivas, algoritmos de AM são aplicados a **conjuntos de dados** de treinamento **rotulados** para induzir um modelo preditivo capaz de predizer, para um novo objeto representado pelos valores de seus atributos preditivos, o valor de seu atributo alvo. Modelos preditivos podem ser utilizados, por exemplo, para, a partir de seus sintomas, predizer o estado de saúde de um paciente. Nessas tarefas, em geral são utilizados algoritmos de AM que seguem o paradigma de aprendizado supervisionado* (FACELLI et al. 2021, pág. 3)







(Conteúdo da Diciplina editado e ajustado a um novo DATASET)


In [ ]:
import pandas as pd
import numpy as np

Considere base de dados: https://www.kaggle.com/datasets/teamincribo/stroke-prediction


**Features:**

'Patient ID' = 'ID do paciente' ,

'Patient Name' = 'Nome do paciente',

'Age' = 'Idade',

'Gender' = 'Gênero',

'Hypertension' = 'Hipertensão',

'Heart Disease' = 'Doença cardíaca',

'Marital Status' = 'Estado civil',

'Work Type' = 'Tipo de trabalho',

'Residence Type' = 'Tipo de residência',

'Average Glucose Level' = 'Nível médio de glicose',

'Body Mass Index (BMI)' = 'Índice de Massa Corporal (IMC)',

'Smoking Status' = Condição de fumante,

'Alcohol Intake' = 'Ingestão de álcool',

'Physical Activity' = 'Atividade física',

'Stroke History' = 'Histórico de AVC',

'Family History of Stroke' = 'História Familiar de AVC',

'Dietary Habits' = 'Hábitos de dieta',

'Stress Levels' = 'Níveis de estresse',

'Blood Pressure Levels' = 'Níveis de pressão arterial',

'Cholesterol Levels' = 'Níveis de colesterol',

'Symptoms' = 'Sintomas',

'Diagnosis' = 'Diagnóstico'


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#Ler o dataset
ds = pd.read_csv("/content/drive/MyDrive/stroke_prediction_dataset.csv", sep=',', encoding='iso-8859-1')
#sep é o separador e encoding é a codificação dos caracteres, normalmente utiliza-se o iso-8859-1, utf-8, latin-1

# **Exploração dos Dados**

In [ ]:
#Visualizar as 5 primeiras linhas
ds.head()

Patient ID       Patient Name  Age Gender  Hypertension  Heart Disease  \
0       18153    Mamooty Khurana   56   Male             0              1   
1       62749  Kaira Subramaniam   80   Male             0              0   
2       32145      Dhanush Balan   26   Male             1              1   
3        6154        Ivana Baral   73   Male             0              0   
4       48973  Darshit Jayaraman   51   Male             1              1   

  Marital Status      Work Type Residence Type  Average Glucose Level  ...  \
0        Married  Self-employed          Rural                 130.91  ...   
1         Single  Self-employed          Urban                 183.73  ...   
2        Married   Never Worked          Rural                 189.00  ...   
3        Married   Never Worked          Urban                 185.29  ...   
4       Divorced  Self-employed          Urban                 177.34  ...   

     Alcohol Intake Physical Activity Stroke History Family History of Stroke  \
0    Social Drinker          Moderate              0                      Yes   
1             Never               Low              0                       No   
2            Rarely              High              0                      Yes   
3  Frequent Drinker          Moderate              0                       No   
4            Rarely               Low              0                      Yes   

   Dietary Habits Stress Levels Blood Pressure Levels  Cholesterol Levels  \
0           Vegan          3.48               140/108   HDL: 68, LDL: 133   
1           Paleo          1.73                146/91    HDL: 63, LDL: 70   
2           Paleo          7.31                154/97    HDL: 59, LDL: 95   
3           Paleo          5.35                174/81   HDL: 70, LDL: 137   
4     Pescatarian          6.84                121/95    HDL: 65, LDL: 68   

                                            Symptoms  Diagnosis  
0                      Difficulty Speaking, Headache     Stroke  
1    Loss of Balance, Headache, Dizziness, Confusion     Stroke  
2                                Seizures, Dizziness     Stroke  
3  Seizures, Blurred Vision, Severe Fatigue, Head...  No Stroke  
4                                Difficulty Speaking     Stroke  

[5 rows x 22 columns]

In [ ]:
ds.describe()

Patient ID           Age  Hypertension  Heart Disease  \
count  15000.000000  15000.000000  15000.000000   15000.000000   
mean   49715.802867     54.035667      0.249000       0.502933   
std    29000.656642     21.063111      0.432448       0.500008   
min        1.000000     18.000000      0.000000       0.000000   
25%    24562.000000     36.000000      0.000000       0.000000   
50%    49448.000000     54.000000      0.000000       1.000000   
75%    75112.000000     72.000000      0.000000       1.000000   
max    99975.000000     90.000000      1.000000       1.000000   

       Average Glucose Level  Body Mass Index (BMI)  Stroke History  \
count           15000.000000           15000.000000    15000.000000   
mean              129.445209              27.474302        0.500267   
std                40.487792               7.230201        0.500017   
min                60.000000              15.010000        0.000000   
25%                94.517500              21.160000        0.000000   
50%               128.900000              27.420000        1.000000   
75%               164.592500              33.720000        1.000000   
max               200.000000              40.000000        1.000000   

       Stress Levels  
count   15000.000000  
mean        5.022694  
std         2.873223  
min         0.000000  
25%         2.540000  
50%         5.050000  
75%         7.520000  
max        10.000000

In [ ]:
ds.dtypes

Patient ID                    int64
Patient Name                 object
Age                           int64
Gender                       object
Hypertension                  int64
Heart Disease                 int64
Marital Status               object
Work Type                    object
Residence Type               object
Average Glucose Level       float64
Body Mass Index (BMI)       float64
Smoking Status               object
Alcohol Intake               object
Physical Activity            object
Stroke History                int64
Family History of Stroke     object
Dietary Habits               object
Stress Levels               float64
Blood Pressure Levels        object
Cholesterol Levels           object
Symptoms                     object
Diagnosis                    object
dtype: object

In [ ]:
#Visualizar as 10 primeiras
ds.head(10)

Patient ID       Patient Name  Age  Gender  Hypertension  Heart Disease  \
0       18153    Mamooty Khurana   56    Male             0              1   
1       62749  Kaira Subramaniam   80    Male             0              0   
2       32145      Dhanush Balan   26    Male             1              1   
3        6154        Ivana Baral   73    Male             0              0   
4       48973  Darshit Jayaraman   51    Male             1              1   
5       29307        Advika Kota   62  Female             0              0   
6       25525      Elakshi Karan   40  Female             1              0   
7        4809        Shalv Dugar   61  Female             0              1   
8        7372       Raghav Handa   72  Female             1              1   
9       37504     Krish Kulkarni   82    Male             0              0   

  Marital Status       Work Type Residence Type  Average Glucose Level  ...  \
0        Married   Self-employed          Rural                 130.91  ...   
1         Single   Self-employed          Urban                 183.73  ...   
2        Married    Never Worked          Rural                 189.00  ...   
3        Married    Never Worked          Urban                 185.29  ...   
4       Divorced   Self-employed          Urban                 177.34  ...   
5         Single         Private          Urban                  91.60  ...   
6        Married         Private          Urban                  77.83  ...   
7       Divorced  Government Job          Rural                 194.73  ...   
8        Married   Self-employed          Rural                  72.99  ...   
9       Divorced   Self-employed          Urban                 111.23  ...   

     Alcohol Intake Physical Activity Stroke History Family History of Stroke  \
0    Social Drinker          Moderate              0                      Yes   
1             Never               Low              0                       No   
2            Rarely              High              0                      Yes   
3  Frequent Drinker          Moderate              0                       No   
4            Rarely               Low              0                      Yes   
5    Social Drinker              High              0                       No   
6             Never               Low              1                       No   
7            Rarely          Moderate              1                       No   
8            Rarely              High              1                       No   
9            Rarely              High              1                      Yes   

   Dietary Habits Stress Levels Blood Pressure Levels  Cholesterol Levels  \
0           Vegan          3.48               140/108   HDL: 68, LDL: 133   
1           Paleo          1.73                146/91    HDL: 63, LDL: 70   
2           Paleo          7.31                154/97    HDL: 59, LDL: 95   
3           Paleo          5.35                174/81   HDL: 70, LDL: 137   
4     Pescatarian          6.84                121/95    HDL: 65, LDL: 68   
5     Gluten-Free          4.85                132/64    HDL: 80, LDL: 69   
6      Vegetarian          6.38               178/105   HDL: 31, LDL: 134   
7           Vegan          5.85                179/72   HDL: 66, LDL: 134   
8      Vegetarian          0.73               141/106   HDL: 71, LDL: 140   
9  Non-Vegetarian          8.39                119/88    HDL: 32, LDL: 88   

                                            Symptoms  Diagnosis  
0                      Difficulty Speaking, Headache     Stroke  
1    Loss of Balance, Headache, Dizziness, Confusion     Stroke  
2                                Seizures, Dizziness     Stroke  
3  Seizures, Blurred Vision, Severe Fatigue, Head...  No Stroke  
4                                Difficulty Speaking     Stroke  
5                                     Severe Fatigue     Stroke  
6                                                NaN  No Stroke  
7     

In [ ]:
#Visualizar as 5 últimas linhas
ds.tail()

Patient ID   Patient Name  Age  Gender  Hypertension  Heart Disease  \
14995       13981      Keya Iyer   88  Female             1              1   
14996       87707   Anahita Virk   47  Female             0              0   
14997       33174     Ivana Kaur   35    Male             0              0   
14998       22343    Anvi Mannan   73    Male             0              0   
14999       11066  Gokul Trivedi   64  Female             0              0   

      Marital Status       Work Type Residence Type  Average Glucose Level  \
14995       Divorced   Self-employed          Urban                 160.22   
14996        Married         Private          Urban                 107.58   
14997        Married  Government Job          Rural                 134.90   
14998         Single   Self-employed          Urban                 169.42   
14999         Single    Never Worked          Urban                 186.88   

       ...  Alcohol Intake Physical Activity Stroke History  \
14995  ...  Social Drinker              High              0   
14996  ...           Never               Low              1   
14997  ...          Rarely              High              1   
14998  ...           Never              High              0   
14999  ...          Rarely          Moderate              0   

      Family History of Stroke  Dietary Habits Stress Levels  \
14995                       No           Paleo          1.12   
14996                       No     Gluten-Free          1.47   
14997                       No           Paleo          0.51   
14998                      Yes           Paleo          1.53   
14999                       No           Vegan          4.57   

      Blood Pressure Levels  Cholesterol Levels  \
14995                171/92   HDL: 44, LDL: 153   
14996                155/71   HDL: 35, LDL: 183   
14997               121/110   HDL: 57, LDL: 159   
14998                157/74    HDL: 79, LDL: 91   
14999                133/81   HDL: 78, LDL: 179   

                                                Symptoms  Diagnosis  
14995                                                NaN  No Stroke  
14996                                Difficulty Speaking  No Stroke  
14997      Difficulty Speaking, Severe Fatigue, Headache     Stroke  
14998  Severe Fatigue, Numbness, Confusion, Dizziness...  No Stroke  
14999                                           Headache     Stroke  

[5 rows x 22 columns]

In [ ]:
#Visualizar as 10 últimas linhas
ds.tail(10)

Patient ID       Patient Name  Age  Gender  Hypertension  \
14990        4140       Nitya Mangal   47  Female             0   
14991       90658        Samaira Raj   26    Male             0   
14992       65220       Bhamini Tara   81  Female             1   
14993       12868  Uthkarsh Dhaliwal   90  Female             1   
14994       36750         Anvi Setty   79  Female             0   
14995       13981          Keya Iyer   88  Female             1   
14996       87707       Anahita Virk   47  Female             0   
14997       33174         Ivana Kaur   35    Male             0   
14998       22343        Anvi Mannan   73    Male             0   
14999       11066      Gokul Trivedi   64  Female             0   

       Heart Disease Marital Status       Work Type Residence Type  \
14990              1         Single    Never Worked          Rural   
14991              1        Married   Self-employed          Rural   
14992              1       Divorced         Private          Rural   
14993              0       Divorced         Private          Urban   
14994              1       Divorced         Private          Rural   
14995              1       Divorced   Self-employed          Urban   
14996              0        Married         Private          Urban   
14997              0        Married  Government Job          Rural   
14998              0         Single   Self-employed          Urban   
14999              0         Single    Never Worked          Urban   

       Average Glucose Level  ...    Alcohol Intake Physical Activity  \
14990                 117.64  ...    Social Drinker          Moderate   
14991                 145.05  ...    Social Drinker               Low   
14992                  60.21  ...            Rarely          Moderate   
14993                 199.79  ...            Rarely               Low   
14994                  82.69  ...  Frequent Drinker               Low   
14995                 160.22  ...    Social Drinker              High   
14996                 107.58  ...             Never               Low   
14997                 134.90  ...            Rarely              High   
14998                 169.42  ...             Never              High   
14999                 186.88  ...            Rarely          Moderate   

      Stroke History Family History of Stroke  Dietary Habits Stress Levels  \
14990              1                      Yes           Vegan          3.67   
14991              1                       No     Pescatarian          0.71   
14992              1                       No  Non-Vegetarian          5.49   
14993              1                      Yes            Keto          2.11   
14994              1                      Yes      Vegetarian          8.69   
14995              0                       No           Paleo          1.12   
14996              1                       No     Gluten-Free          1.47   
14997              1                       No           Paleo          0.51   
14998              0                      Yes           Paleo          1.53   
14999              0                       No           Vegan          4.57   

      Blood Pressure Levels  Cholesterol Levels  \
14990                156/70    HDL: 43, LDL: 94   
14991               180/110    HDL: 33, LDL: 99   
14992                160/73   HDL: 50, LDL: 174   
14993                108/61   HDL: 80, LDL: 162   
14994                100/99    HDL: 60, LDL: 65   
14995                171/92   HDL: 44, LDL: 153   
14996                155/71   HDL: 35, LDL: 183   
14997               121/110   HDL: 57, LDL: 159   
14998                157/74    HDL: 79, LDL: 91   
14999                133/81   HDL: 78, LDL: 179   

                                                Symptoms  Diagnosis  
14990                                                NaN     Stroke  
14991                               Confusion, Confusion  No Stroke  
14992                                    Loss of Bal

In [ ]:
#Visualizar a quantidade de linhas e colunas do conjunto de dados - Shape retorna a dimensão do DataFrame (linhas, colunas)
ds.shape

(15000, 22)

# **Transformando dados categóricos em dados numéricos**

A maioria dos algoritmos de Machine Learning trabalham melhor com dados numéricos.

In [ ]:
ds2 = pd.DataFrame.copy(ds)

In [ ]:
#Visualizar os tipos dos dados e a quantidade de dados não nulos
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Patient ID                15000 non-null  int64  
 1   Patient Name              15000 non-null  object 
 2   Age                       15000 non-null  int64  
 3   Gender                    15000 non-null  object 
 4   Hypertension              15000 non-null  int64  
 5   Heart Disease             15000 non-null  int64  
 6   Marital Status            15000 non-null  object 
 7   Work Type                 15000 non-null  object 
 8   Residence Type            15000 non-null  object 
 9   Average Glucose Level     15000 non-null  float64
 10  Body Mass Index (BMI)     15000 non-null  float64
 11  Smoking Status            15000 non-null  object 
 12  Alcohol Intake            15000 non-null  object 
 13  Physical Activity         15000 non-null  object 
 14  Stroke

**Tipo de atributos:**

object: string

int64: inteiros

float64: reais

complex: complexos

In [ ]:
#Verificar a contagem de frequência de cada classe do atributo Age.
ds2['Age'].value_counts()

33    244
45    236
89    232
75    229
68    228
     ... 
56    181
44    179
81    179
60    177
80    173
Name: Age, Length: 73, dtype: int64

In [ ]:
#Verificar a contagem de frequência de cada classe do atributo
ds2['Smoking Status'].value_counts()

Currently Smokes    5011
Non-smoker          5009
Formerly Smoked     4980
Name: Smoking Status, dtype: int64

Verificando a existência de valor nulos, ou faltantes (NAN):

In [ ]:
ds2.isnull().sum()
#Se existir, verificar a necesidade de exclusão (ds2.dropna()) ou
#substiruição por outro valor específico (média, moda, mediana) usando ds2['nomecol'].fillna(valor,inplace=True)


Patient ID                     0
Patient Name                   0
Age                            0
Gender                         0
Hypertension                   0
Heart Disease                  0
Marital Status                 0
Work Type                      0
Residence Type                 0
Average Glucose Level          0
Body Mass Index (BMI)          0
Smoking Status                 0
Alcohol Intake                 0
Physical Activity              0
Stroke History                 0
Family History of Stroke       0
Dietary Habits                 0
Stress Levels                  0
Blood Pressure Levels          0
Cholesterol Levels             0
Symptoms                    2500
Diagnosis                      0
dtype: int64

In [ ]:
colunas_para_remover = ['Patient Name','Symptoms','Cholesterol Levels','Blood Pressure Levels']
ds2 = ds2.drop(columns=colunas_para_remover)
ds2.isnull().sum()

Patient ID                  0
Age                         0
Gender                      0
Hypertension                0
Heart Disease               0
Marital Status              0
Work Type                   0
Residence Type              0
Average Glucose Level       0
Body Mass Index (BMI)       0
Smoking Status              0
Alcohol Intake              0
Physical Activity           0
Stroke History              0
Family History of Stroke    0
Dietary Habits              0
Stress Levels               0
Diagnosis                   0
dtype: int64

Realizar a transformação de dados categóricos em numéricos manualmente.

In [ ]:
#replace - substitui os valores um DataFrame por outros valores de forma dinâmica.
ds2['Diagnosis'].replace({'No Stroke':0, 'Stroke': 1}, inplace=True)
ds2['Gender'].replace({'Male':0, 'Female': 1}, inplace=True)
ds2['Marital Status'].replace({'Single':0, 'Married': 1, 'Divorced' :2}, inplace=True)
ds2['Residence Type'].replace({'Rural':0, 'Urban': 1}, inplace=True)
ds2['Work Type'].replace({'Private':0, 'Self-employed': 1, 'Government Job':2 ,'Never Worked':3}, inplace=True)
ds2['Alcohol Intake'].replace({'Rarely':0,'Social Drinker':1,'Never':2,'Frequent Drinker':3}, inplace=True)
ds2['Physical Activity'].replace({'High':0,'Moderate':1,'Low':2}, inplace=True)
ds2['Family History of Stroke'].replace({'Yes':0,'No':1}, inplace=True)
ds2['Dietary Habits'].replace({'Paleo':0,'Vegan':1,'Vegetarian':2,'Non-Vegetarian':3 ,'Keto': 4 ,'Pescatarian':5,'Gluten-Free':6 }, inplace=True)
ds2['Smoking Status'].replace({'Currently Smokes':0,'Non-smoker':1,'Formerly Smoked':2}, inplace=True)
#inplace: altera definitivamente, padrão é none.

In [ ]:
ds2.head()

Patient ID  Age  Gender  Hypertension  Heart Disease  Marital Status  \
0       18153   56       0             0              1               1   
1       62749   80       0             0              0               0   
2       32145   26       0             1              1               1   
3        6154   73       0             0              0               1   
4       48973   51       0             1              1               2   

   Work Type  Residence Type  Average Glucose Level  Body Mass Index (BMI)  \
0          1               0                 130.91                  22.37   
1          1               1                 183.73                  32.57   
2          3               0                 189.00                  20.32   
3          3               1                 185.29                  27.50   
4          1               1                 177.34                  29.06   

   Smoking Status  Alcohol Intake  Physical Activity  Stroke History  \
0               1               1                  1               0   
1               1               2                  2               0   
2               2               0                  0               0   
3               1               3                  1               0   
4               0               0                  2               0   

   Family History of Stroke  Dietary Habits  Stress Levels  Diagnosis  
0                         0               1           3.48          1  
1                         1               0           1.73          1  
2                         0               0           7.31          1  
3                         1               0           5.35          0  
4                         0               5           6.84          1

In [ ]:
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Patient ID                15000 non-null  int64  
 1   Age                       15000 non-null  int64  
 2   Gender                    15000 non-null  int64  
 3   Hypertension              15000 non-null  int64  
 4   Heart Disease             15000 non-null  int64  
 5   Marital Status            15000 non-null  int64  
 6   Work Type                 15000 non-null  int64  
 7   Residence Type            15000 non-null  int64  
 8   Average Glucose Level     15000 non-null  float64
 9   Body Mass Index (BMI)     15000 non-null  float64
 10  Smoking Status            15000 non-null  int64  
 11  Alcohol Intake            15000 non-null  int64  
 12  Physical Activity         15000 non-null  int64  
 13  Stroke History            15000 non-null  int64  
 14  Family

In [ ]:
ds2.shape


(15000, 18)

In [ ]:
#previsores = conjunto de variáveis previsoras com as variáveis categóricas transformadas em numéricas manualmente (são os dados entrada).
previsores = ds2.iloc[:, 0:17].values
#iloc - df.iloc[<linhas>, <colunas>],
#neste exemplo, tem-se uma seleção de múltiplas linhas e colunas, no caso, todos os dados a partir da primeira coluna até a 17ª coluna,
#o retorno é um Pandas DataFrame.

In [ ]:
#Dados de entrada
previsores

array([[1.8153e+04, 5.6000e+01, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        3.4800e+00],
       [6.2749e+04, 8.0000e+01, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.7300e+00],
       [3.2145e+04, 2.6000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        7.3100e+00],
       ...,
       [3.3174e+04, 3.5000e+01, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        5.1000e-01],
       [2.2343e+04, 7.3000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.5300e+00],
       [1.1066e+04, 6.4000e+01, 1.0000e+00, ..., 1.0000e+00, 1.0000e+00,
        4.5700e+00]])

In [ ]:
previsores.shape

(15000, 17)

In [ ]:
#alvo = variável que se pretende atingir - tem ou não doença cardíaca (são os dados de saída)).
alvo = ds2.iloc[:,17].values
# ou alvo = ds2.iloc[:, -1].values

In [ ]:
#Dados de saída
alvo

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
alvo.shape

(15000,)

# **Base de Treino e Teste**

O **scikit-learn** é uma biblioteca da linguagem Python para machine learning.

https://scikit-learn.org/stable/

In [ ]:
from sklearn.model_selection import train_test_split
#Usado para dividir os dados em subconjuntos aleatórios de treinamento e teste.

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size = 0.20, random_state = 123)
#test_size: tamanho em porcentagem dos dados de teste. default é none.
#random_state: controla o embaralhamento aplicado aos dados antes de aplicar a divisão.
#              É a nomeação de um estado aleatório (pata termos sempre o mesmo conjunto de treino e teste para poder comprar
#              qual é o melhor algoritmo, random_state = 0).

In [ ]:
#x_treino
x_treino.shape

(12000, 17)

In [ ]:
#x_teste
x_teste.shape

(3000, 17)

In [ ]:
#y_treino
y_treino.shape

(12000,)

In [ ]:
#y_teste
y_teste.shape

(3000,)

Importar as bibliotecas para métricas de avaliação e validação cruzada:


In [ ]:
# Para as métricas de avaliação dos modelos
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

**accuracy_score:** pontuação de classificação de precisão.

**confusion_matrix:** matriz de confusão para avaliar a precisão de uma classificação.

**classification_report**: apresenta um relatório das métricas da classificação. Apresenta as métricas precision, recall, F1-score para cada classe.




















In [ ]:
#Para validação cruzada
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
#Definir as folds para validação cruzada

In [ ]:
kfold = KFold(n_splits = 20, shuffle=True, random_state = 42)
#n_splis=5 (default)
#shuffle: se deve embaralhar os dados antes de dividir em lotes (as amostras dentro de cada divisão não serão embaralhadas)

# **Aprendizagem Baseada em Instâncias (KNN)**

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.DistanceMetric.html

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Criando o modelo
knn = KNeighborsClassifier(n_neighbors=18, metric ='minkowski', p=1) #p=1, usa a a manhatan, 2=euclidiana
# knn = KNeighborsClassifier(n_neighbors=15, metric ='minkowski', p=2) #p=1, usa a a manhatan, 2=euclidiana
# knn = KNeighborsClassifier(n_neighbors=3, metric ='minkowski', p=2) #p=1, usa a a manhatan, 2=euclidiana
# knn = KNeighborsClassifier(n_neighbors=1, metric ='minkowski', p=2) #p=1, usa a a manhatan, 2=euclidiana
#Treinando o modelo
knn.fit(x_treino, y_treino)

KNeighborsClassifier(n_neighbors=18, p=1)

In [ ]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([1, 0, 0, ..., 1, 0, 0])

In [ ]:
y_teste


array([0, 0, 0, ..., 1, 1, 0])

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_knn) * 100.0))
print("Acurácia (quantidade amostras): %.2f" % (accuracy_score(y_teste, previsoes_knn, normalize=False) ))
#normalize: default=True. Se False, retorna o número de amostras classificadas corretamente

Acurácia: 51.07%
Acurácia (quantidade amostras): 1532.00


In [ ]:
confusion_matrix(y_teste, previsoes_knn)

#array([[29, 11],
#       [12, 40]])

array([[958, 572],
       [896, 574]])

In [ ]:
print(classification_report(y_teste, previsoes_knn))

              precision    recall  f1-score   support

           0       0.52      0.63      0.57      1530
           1       0.50      0.39      0.44      1470

    accuracy                           0.51      3000
   macro avg       0.51      0.51      0.50      3000
weighted avg       0.51      0.51      0.50      3000



In [ ]:
print(classification_report(y_teste, previsoes_knn, target_names=['Não possui chance de ter AVC','Possui doença chance de ter AVC'],digits=4))
#target_names: default=None. Nomes de exibição opcionais dos rótulos.
#digits:default=2. Número de dígitos para formatar os dados de saída.

                                 precision    recall  f1-score   support

   Não possui chance de ter AVC     0.5167    0.6261    0.5662      1530
Possui doença chance de ter AVC     0.5009    0.3905    0.4388      1470

                       accuracy                         0.5107      3000
                      macro avg     0.5088    0.5083    0.5025      3000
                   weighted avg     0.5090    0.5107    0.5038      3000



**Validação Cruzada**

In [ ]:
# Criando o modelo para validação cruzada
knnVC1 = KNeighborsClassifier(n_neighbors=18, metric='minkowski', p = 2)
knnVC2 = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p = 1)
knnVC3 = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p = 2)

resultado1 = cross_val_score(knnVC1, previsores, alvo, cv = kfold)
resultado2 = cross_val_score(knnVC2, previsores, alvo, cv = kfold)
resultado3 = cross_val_score(knnVC3, previsores, alvo, cv = kfold)
#cv=None, validação cruzada padrão de 5 vezes

# Usando a média e o desvio padrão
print("18 = Acurácia Média: %.2f%%" % (resultado1.mean() * 100.0))
print("5 = Acurácia Média: %.2f%%" % (resultado2.mean() * 100.0))
print("3 = Acurácia Média: %.2f%%" % (resultado3.mean() * 100.0))

18 = Acurácia Média: 50.19%
5 = Acurácia Média: 49.54%
3 = Acurácia Média: 49.58%


# **NAIVE BAYES**
https://scikit-learn.org/stable/modules/naive_bayes.html

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB

In [ ]:
#Criando o modelo
# naive = GaussianNB()
naive =  BernoulliNB()
#Treinando o modelo
naive.fit(x_treino, y_treino)

BernoulliNB()

In [ ]:
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([0, 0, 1, ..., 1, 1, 1])

In [ ]:
y_teste

array([0, 0, 0, ..., 1, 1, 0])

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_naive) * 100.0))

Acurácia: 51.10%


In [ ]:
confusion_matrix(y_teste, previsoes_naive)

array([[789, 741],
       [726, 744]])

In [ ]:
print(classification_report(y_teste, previsoes_naive))

              precision    recall  f1-score   support

           0       0.52      0.52      0.52      1530
           1       0.50      0.51      0.50      1470

    accuracy                           0.51      3000
   macro avg       0.51      0.51      0.51      3000
weighted avg       0.51      0.51      0.51      3000



**Validação Cruzada**

In [ ]:
# Criando o modelo para validação cruzada
naiveVC = GaussianNB()
resultado = cross_val_score(naiveVC, previsores, alvo, cv = kfold)
resultado

array([0.52666667, 0.51866667, 0.524     , 0.484     , 0.49466667,
       0.49866667, 0.51466667, 0.488     , 0.51066667, 0.50266667,
       0.50933333, 0.48933333, 0.52133333, 0.48      , 0.46666667,
       0.5       , 0.53466667, 0.508     , 0.50666667, 0.54      ])

In [ ]:
# Usando a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 50.59%


Naive Bayes = 84,42% (treino e teste) - 233 acertos e 85,06% (validação cruzada)

# **ÁRVORE DE DECISÃO**
https://scikit-learn.org/stable/modules/tree.html

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# arvore = DecisionTreeClassifier(criterion='entropy', random_state = 0)
#arvore = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state = 0)
#arvore = DecisionTreeClassifier(criterion='gini',random_state = 0)
#arvore = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state = 0)
arvore = RandomForestClassifier(n_estimators=10)

#criterion: função para medir a qualidade da divisão, {“gini”, “entropia”, “log_loss”}, default=”gini”. Métricas como entropia, que é a medida da
#           falta de homogeneidade, e o índice de Gini, que é a medida do grau de heterogeneidade, são usdas para determinar o nível de importância
#           de um atributo (chamado de ganho de informação)
#max_depth=3: profundidade máxima da árvore (poda), se None, sem poda

arvore.fit(x_treino, y_treino)

RandomForestClassifier(n_estimators=10)

In [ ]:
previsoes_arvore = arvore.predict(x_teste)


In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_arvore) * 100.0))

Acurácia: 49.40%


In [ ]:
confusion_matrix(y_teste, previsoes_arvore)

array([[941, 589],
       [929, 541]])

In [ ]:
print(classification_report(y_teste, previsoes_arvore))

              precision    recall  f1-score   support

           0       0.50      0.62      0.55      1530
           1       0.48      0.37      0.42      1470

    accuracy                           0.49      3000
   macro avg       0.49      0.49      0.48      3000
weighted avg       0.49      0.49      0.49      3000



Analisando os dados de treinamento

In [ ]:
previsoes_treino = arvore.predict(x_treino)


In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino, previsoes_treino)* 100.0))

Acurácia: 98.52%


In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[5973,   29],
       [ 148, 5850]])

A acurácia 100% indica que o modelo se ajustou muito bem com os dados de treinamento, mas com os dados de teste, o resultado é ruim. Quando isso ocorre é dito que o modelo aprendeu demais sobre os dados de treinamento, ele decorou. Isso é chamado de **overfitting**, ou sobreajuste. Uma forma de tentar resolver é configurar o hiperparâmetro max_depth, que é a profundidade máxima da árvore, significa fazer poda.

**Validação Cruzada**

In [ ]:
# Criando o modelo
modelo = DecisionTreeClassifier(criterion='entropy', random_state = 0)
#modelo = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state = 0)
#modelo = DecisionTreeClassifier(criterion='gini',random_state = 0)
#modelo = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state = 0)

resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 49.78%


# **SVM - MÁQUINAS DE VETORES DE SUPORTE**

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In [ ]:
from sklearn.svm import SVC
#SVC = classificador de vetor de suporte

In [ ]:
svm = SVC(kernel='rbf', random_state=0, C = 2)
# svm = SVC(kernel='poly', random_state=0, C = 2)
#svm = SVC(kernel='sigmoid', random_state=0, C = 2)
# svm = SVC(kernel='linear', random_state=0, C = 2)
# svm = SVC(kernel='linear', random_state=0, C = 40)

# hiperparâmetro kernel: transforma os dados. Default: rbf
# hiperparâmetro C: constante de penalização, controla a tolerância de erros. Quanto maior o valor de C, maior capacidade de separação das classes,
#                   porém, maior probabilidade de overfitting e tempo de treinamento. Default = 1.
svm.fit(x_treino, y_treino)

SVC(C=2, random_state=0)

In [ ]:
previsoes_svm = svm.predict(x_teste)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))

Acurácia: 49.67%


In [ ]:
confusion_matrix(y_teste, previsoes_svm)

array([[1320,  210],
       [1300,  170]])

In [ ]:
print(classification_report(y_teste, previsoes_svm))

              precision    recall  f1-score   support

           0       0.50      0.86      0.64      1530
           1       0.45      0.12      0.18      1470

    accuracy                           0.50      3000
   macro avg       0.48      0.49      0.41      3000
weighted avg       0.48      0.50      0.41      3000



Analisando os dados de treinamento

In [ ]:
previsoes_treino = svm.predict(x_treino)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino, previsoes_treino)* 100.0))

Acurácia: 50.05%


In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[5252,  750],
       [5244,  754]])

**Validação Cruzada**

In [ ]:
# Criando o modelo
modelo = SVC(kernel='rbf', random_state=0, C = 2)
#modelo = SVC(kernel='poly', random_state=0, C = 2)
#modelo = SVC(kernel='sigmoid', random_state=0, C = 2)
#modelo = SVC(kernel='linear', random_state=0, C = 2)
#modelo = SVC(kernel='linear', random_state=0, C = 40)
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 49.39%


# **RNA - REDE NEURAL ARTIFICIAL**

https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
#Criando o modelo
redes = MLPClassifier(hidden_layer_sizes=(10,10), activation='logistic', max_iter =800,random_state = 0, verbose = True)
#redes = MLPClassifier(hidden_layer_sizes=(17), activation='logistic', max_iter =800, random_state = 0, verbose = True)

#hidden_layer_sizes (camadas escondidas): default (100,). Não exagerar, geralmente 2 já apresenta bons resultados. Para conjuntos de dados pequenos, uma já é suficiente.
#                                         Quant.= (Ne+Ns)/2 = (11+1)/2 = 6 neurônios Quant.=2.Ne/3 + Ns = 2.11/3 + 1 = 8 neurônios (nº de neurônios nas camadas escondidas).
#                                         Neurônios em excesso provocam overfitting, poucos provocam underfitting
#activation: Função de ativação default='relu'
#max_iter int: Número máximo de iterações. default = 200. (número de épocas). Excesso provoca overfitting. Sugere-se valores entre 500 e 3000 ciclos de treinamento
#random_state = 0, garantir que os dados do embaralhamento sejam sempre os mesmos para poder testar diferentes algoritimos.
#verbose: Mostra o progresso. default=False.



In [ ]:
#Treinando o modelo
redes.fit(x_treino, y_treino)

Iteration 1, loss = 0.70181261
Iteration 2, loss = 0.69326247
Iteration 3, loss = 0.69318862
Iteration 4, loss = 0.69331117
Iteration 5, loss = 0.69329863
Iteration 6, loss = 0.69319474
Iteration 7, loss = 0.69318936
Iteration 8, loss = 0.69318833
Iteration 9, loss = 0.69323101
Iteration 10, loss = 0.69317030
Iteration 11, loss = 0.69316019
Iteration 12, loss = 0.69314693
Iteration 13, loss = 0.69315620
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPClassifier(activation='logistic', hidden_layer_sizes=(10, 10), max_iter=800,
              random_state=0, verbose=True)

In [ ]:
previsoes = redes.predict(x_teste)

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes) * 100.0))

Acurácia: 50.83%


In [ ]:
confusion_matrix(y_teste, previsoes)

array([[1521,    9],
       [1466,    4]])

In [ ]:
print(classification_report(y_teste, previsoes))

              precision    recall  f1-score   support

           0       0.51      0.99      0.67      1530
           1       0.31      0.00      0.01      1470

    accuracy                           0.51      3000
   macro avg       0.41      0.50      0.34      3000
weighted avg       0.41      0.51      0.35      3000



Analisando os dados de treinamento

In [ ]:
previsoes_treino = redes.predict(x_treino)
previsoes_treino

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino, previsoes_treino)* 100.0))

Acurácia: 50.15%


In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[5989,   13],
       [5969,   29]])

**Validação Cruzada**

In [ ]:
# Criando o modelo para validação cruzada
#redesVC = MLPClassifier(hidden_layer_sizes=(17), activation='relu', max_iter =800, random_state = 0, verbose = True)
redesVC = MLPClassifier(hidden_layer_sizes=(17), activation='logistic',  max_iter =800, random_state = 0, verbose = True)
resultado = cross_val_score(redesVC, previsores, alvo, cv = kfold)


Iteration 1, loss = 0.72706675
Iteration 2, loss = 0.69425077
Iteration 3, loss = 0.69332555
Iteration 4, loss = 0.69318860
Iteration 5, loss = 0.69304072
Iteration 6, loss = 0.69344824
Iteration 7, loss = 0.69315038
Iteration 8, loss = 0.69300465
Iteration 9, loss = 0.69294620
Iteration 10, loss = 0.69291901
Iteration 11, loss = 0.69299846
Iteration 12, loss = 0.69290889
Iteration 13, loss = 0.69287773
Iteration 14, loss = 0.69292786
Iteration 15, loss = 0.69291149
Iteration 16, loss = 0.69291136
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Iteration 1, loss = 0.72816144
Iteration 2, loss = 0.69427886
Iteration 3, loss = 0.69307008
Iteration 4, loss = 0.69308454
Iteration 5, loss = 0.69300361
Iteration 6, loss = 0.69296159
Iteration 7, loss = 0.69289237
Iteration 8, loss = 0.69290331
Iteration 9, loss = 0.69296468
Iteration 10, loss = 0.69294224
Iteration 11, loss = 0.69290429
Iteration 12, loss = 0.69296565
Iteration 13, loss = 0.69303249


In [ ]:
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 49.87%
